
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./project:/app/symfony
    environment:
      SYMFONY_ENV: dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - .:/app/symfony:rw,cached
volumes:
  mysql_data: